---
name: diamond_fm_app
description: A new Flutter project.
publish_to: none
version: 1.0.4+5
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: 4.1.2
  webview_flutter: ^1.0.7
  http: ^0.13.0
  html: ^0.14.0+4
  volume: ^1.0.1
  volume_control: ^0.1.3
  font_awesome_flutter: ^8.11.0
  cupertino_icons: ^1.0.0
  streaming_radio_flutter_plugin: ^3.0.2
dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/squarelogo.png
flutter:
  uses-material-design: true
  assets:
  - assets/
  fonts:
  - family: Axiforma
    fonts:
    - asset: assets/fonts/Axiforma-Regular.ttf
    - asset: assets/fonts/Axiforma-Light.ttf
      weight: 300
    - asset: assets/fonts/Axiforma-Medium.ttf
      weight: 500
    - asset: assets/fonts/Axiforma-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Axiforma-Bold.ttf
      weight: 700
    - asset: assets/fonts/Axiforma-ExtraBold.ttf
      weight: 800
